schema:
    - http://localhost:8000/graphql
documents:
    - schemas/**/*.graphql
extensions:
    codegen:
        generates:
            ./__generated__/schemas/:
                preset: client
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
        presetConfig:
            gqlTagName: gql
        ignoreNoDocuments: true
        verbose: true
overwrite: true
