schema:
    - ./schemas/sdl.graphql
documents:
    - schemas/**/*.gql
extensions:
    codegen:
        generates:
            ./__generated__/schemas/:
                preset: client
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
        presetConfig:
            gqlTagName: gql
        ignoreNoDocuments: true
        verbose: true
overwrite: true
