mutation CreateFolderPermission($input: CreateFolderPermissionInput!) {
    folderPermission {
        create(input: $input) {
            id
            role
            user {
                id
                email
            }
        }
    }
}
