query GetFolderContents($folderId: UUID) {
    folder {
        getAll(parentId: $folderId) {
            id
            name
            createdAt
        }
    }
    file {
        getAll(folderId: $folderId) {
            id
            name
            size
            mimeType
            ext
            createdAt
        }
    }
}
