query GetFolder($id: UUID!) {
    folder {
        get(id: $id) {
            name
            id
            createdAt
            updatedAt
            path
            files {
                id
                name
                file
                ext
                mimeType
                size
                starred
                createdAt
                updatedAt
            }
            folders {
                id
                name
                createdAt
                updatedAt
            }
        }
    }
}
