mutation UpdateFolderPermission($input: UpdateFolderPermissionInput!) {
  folderPermission {
    update(
      input: $input
    ) {
      id
      role
      user {
        email
        id
      }
    }
  }
}
